- name: install python
  dnf:
    name: python
    state: latest

- name: install pip
  dnf:
    name: python-pip
    state: latest
    disable_gpg_check: yes

- name: uninstall PyYAML
  rmp:
    name: PyYAML 
    state: absent

- name: pip upgrade
  pip:
    name:
      - pip
      - setuptools
      - wheel
      - PyYAML 
    extra_args: --upgrade

- name: pip install docker
  pip:
    name:
      - docker
      - docker-compose
    state: latest
    extra_args: -v


- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
