- name: install python
  dnf:
    name: python
    state: latest

- name: install pip
  dnf:
    name: python-pip
    state: latest
    disable_gpg_check: yes

- name: pip upgrade
  pip:
    name:
      - pip
      - setuptools
      - wheel
    extra_args: --upgrade

- name: Remove pyyaml RPM packages
  yum:
    name: pyyaml==6.0.1
    state: absent

- name: pip install docker
  pip:
    name:
      - docker
      - pyyaml==5.3.1
      - docker-compose
    state: present

- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
